# Generated by Django 4.0.8 on 2022-10-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='statuses',
            field=models.BooleanField(default=False),
        ),
    ]
