# Generated by Django 4.0.8 on 2022-10-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_attendance_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='statuses',
        ),
    ]
