# Generated by Django 4.1.2 on 2022-10-14 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('lecturers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerinfo',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturer_modules', to='students.studentmodules'),
        ),
    ]
